### ISSUE TITLE
No menu in Marketing -> run_as_root -> Google Shopping Feed in magento 2.4.6

### ISSUE THREAD

**Issue by cptX** [run-as-root/Magento-2-Google-Shopping-Feed#4]
I don't see any menu in Marketing -> run_as_root -> Google Shopping Feed in magento 2.4.6
even I did see the generated feeds in the file system.
This is a test site so I don't have cron for this running. I triggered the generation of the files by running cron manually. I don't know if this has something to do...

**Comment by riconeitzel** [comment]
Just to be sure: did you run the deployment processed and cleared the caches (incl. browser caches)?

**Comment by cristiano-pacheco** [comment]
@riconeitzel, the code that adds the menu and controller is not published on Packagist.

When I install the module through the `composer require...` command, version 1.3.0 is installed, if you take a closer look in the source code of this version, you'll notice that there is no menu.xml and routes.xml file within the `etc/adminhtml` folder.

I recommend removing the  `version` attribute from the `composer.json` file and generating a new tag. The issue should be resolved with it.

**Comment by cptX** [comment]
> Just to be sure: did you run the deployment processed and cleared the caches (incl. browser caches)?

Sorry for the late answer, yes I tried everything. According to @cristiano-pacheco probably the issue was not on my side...

**Comment by riconeitzel** [comment]
@DavidLambauer can you publish the latest version on packagist, please?

**Comment by DavidLambauer** [comment]
done
